#+TITLE: Timus 1293 Eniya
#+AUTHOR: Arka Barua
#+PROPERTY: header-args :tangle main.c
#+DATE:Sat Dec 10 10:15:28 2022

* Problem Description
[[https://acm.timus.ru/problem.aspx?space=1&num=1293][Timus 1293]]
We need to calculate how much sulphide is needed to make a panel.
 It is known that the processing of the one square meter of the panel needs 1 nanogramm of sulphide. In general, it is needed to process N rectangular panels, which dimensions are A by B meters.
Do not forget, that the panels need processing of both sides.
** Input
The only line contains integers N (1 ≤ N ≤ 100), A (1 ≤ A ≤ 100), B (1 ≤ B ≤ 100).
** Output
Output the weight of thorium sulphide in nanogramms needed for the processing.
** Sample
| Input | Output |
|-------+--------|
| 5  2 3 |     60 |
* Solution
** Header Files
We will only use the stdio header file for this problem.
#+begin_src c
#include<stdio.h>
#+end_src
** Calculate Function
This functions variables are
- n : the number of rectangular
- a & b: dimensions
- 2 : a constant because we need to process both sides.
  #+begin_src c

int calcualte(int n, int a, int b)
{
    return n * a * b * 2;
}
  #+end_src
** Main Function
#+begin_src c
int main() {
  int n, a, b;
  scanf("%d %d %d", &n, &a, &b);
  printf("%d\n", calcualte(n, a, b));
  return 0;
}
#+end_src
